# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import text_storage_pb2 as text__storage__pb2


class TextStorageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StoreText = channel.unary_unary(
                '/textstorage.TextStorageService/StoreText',
                request_serializer=text__storage__pb2.TextRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetTimestamp = channel.unary_unary(
                '/textstorage.TextStorageService/GetTimestamp',
                request_serializer=text__storage__pb2.TextRequest.SerializeToString,
                response_deserializer=text__storage__pb2.TimestampResponse.FromString,
                )
        self.QueryText = channel.unary_unary(
                '/textstorage.TextStorageService/QueryText',
                request_serializer=text__storage__pb2.TextRequest.SerializeToString,
                response_deserializer=text__storage__pb2.TimestampResponse.FromString,
                )


class TextStorageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StoreText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTimestamp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TextStorageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StoreText': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreText,
                    request_deserializer=text__storage__pb2.TextRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetTimestamp': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTimestamp,
                    request_deserializer=text__storage__pb2.TextRequest.FromString,
                    response_serializer=text__storage__pb2.TimestampResponse.SerializeToString,
            ),
            'QueryText': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryText,
                    request_deserializer=text__storage__pb2.TextRequest.FromString,
                    response_serializer=text__storage__pb2.TimestampResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'textstorage.TextStorageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TextStorageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StoreText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/textstorage.TextStorageService/StoreText',
            text__storage__pb2.TextRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTimestamp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/textstorage.TextStorageService/GetTimestamp',
            text__storage__pb2.TextRequest.SerializeToString,
            text__storage__pb2.TimestampResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/textstorage.TextStorageService/QueryText',
            text__storage__pb2.TextRequest.SerializeToString,
            text__storage__pb2.TimestampResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
